### ISSUE TITLE
 java.lang.VerifyError: com/trello/rxlifecycle/components/support/RxAppCompatActivity

### ISSUE THREAD

**Issue by dreamlivemeng** [trello/RxLifecycle#188]
12-01 20:04:38.074 17433-17433/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.junze.cn.preciousbabyfluppro, PID: 17433
                                                   java.lang.VerifyError: com/trello/rxlifecycle/components/support/RxAppCompatActivity
                                                       at java.lang.Class.newInstanceImpl(Native Method)
                                                       at java.lang.Class.newInstance(Class.java:1208)
                                                       at android.app.Instrumentation.newActivity(Instrumentation.java:1068)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2186)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2378)
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:155)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1244)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5433)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by dlew** [comment]
VerifyError is most likely a build problem on your end. If you can create a sample that reproduces it then I'll look into it.

**Comment by xutao2388** [comment]
https://github.com/CreativeSDK/android-getting-started-samples/issues/33

**Comment by xutao2388** [comment]
solved by MultiDex ；
see：https://github.com/CreativeSDK/android-getting-started-samples/issues/33
