### ISSUE TITLE
 java.lang.VerifyError: com/trello/rxlifecycle2/components/support/RxAppCompatActivity

### ISSUE THREAD

**Issue by chenzhentao** [trello/RxLifecycle#278]
在5.0以下手机运行时突然报错
08-11 17:26:00.099 9361-9361/com.szwyx.rxb W/dalvikvm: Unable to resolve superclass of Lio/reactivex/subjects/BehaviorSubject; (8148)
    Link of class 'Lio/reactivex/subjects/BehaviorSubject;' failed
08-11 17:26:00.099 9361-9361/com.szwyx.rxb W/dalvikvm: VFY: unable to resolve static method 55813: Lio/reactivex/subjects/BehaviorSubject;.create ()Lio/reactivex/subjects/BehaviorSubject;
08-11 17:26:00.099 9361-9361/com.szwyx.rxb W/dalvikvm: Unable to resolve superclass of Lio/reactivex/subjects/BehaviorSubject; (8148)
    Link of class 'Lio/reactivex/subjects/BehaviorSubject;' failed
08-11 17:26:00.100 9361-9361/com.szwyx.rxb W/dalvikvm: VFY: Ljava/lang/Object; is not instance of Lio/reactivex/Observable;
    VFY: bad arg 0 (into Lio/reactivex/Observable;)
    VFY:  rejecting call to Lcom/trello/rxlifecycle2/android/RxLifecycleAndroid;.bindActivity (Lio/reactivex/Observable;)Lcom/trello/rxlifecycle2/LifecycleTransformer;
    VFY:  rejecting opcode 0x71 at 0x0002
    VFY:  rejected Lcom/trello/rxlifecycle2/components/support/RxAppCompatActivity;.bindToLifecycle ()Lcom/trello/rxlifecycle2/LifecycleTransformer;
    Verifier rejected class Lcom/trello/rxlifecycle2/components/support/RxAppCompatActivity;
    Class init failed in newInstance call (Lcom/szwyx/rxb/login/LoginActivity;)
08-11 17:26:00.101 9361-9361/com.szwyx.rxb W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41aeace0)
    threadid=1: uncaught exception occurred
08-11 17:26:00.101 9361-9361/com.szwyx.rxb W/System.err: java.lang.VerifyError: com/trello/rxlifecycle2/components/support/RxAppCompatActivity
        at java.lang.Class.newInstanceImpl(Native Method)
        at java.lang.Class.newInstance(Class.java:1215)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2363)
08-11 17:26:00.102 9361-9361/com.szwyx.rxb W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2526)
        at android.app.ActivityThread.access$800(ActivityThread.java:174)
08-11 17:26:00.102 9361-9361/com.szwyx.rxb W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:222)
        at android.app.ActivityThread.main(ActivityThread.java:5484)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676)
        at dalvik.system.NativeStart.main(Native Method)
08-11 17:26:00.102 9361-9361/com.szwyx.rxb W/dalvikvm: threadid=1: calling UncaughtExceptionHandler
08-11 17:26:00.128 9361-9407/com.szwyx.rxb W/MediatekClassFactory: Tablet not exist!, Get obj from default class
08-11 17:26:00.144 9361-9361/com.szwyx.rxb E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.szwyx.rxb, PID: 9361
    java.lang.VerifyError: com/trello/rxlifecycle2/components/support/RxAppCompatActivity
        at java.lang.Class.newInstanceImpl(Native Method)
        at java.lang.Class.newInstance(Class.java:1215)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2363)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2526)
        at android.app.ActivityThread.access$800(ActivityThread.java:174)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:222)
        at android.app.ActivityThread.main(ActivityThread.java:5484)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676)
        at dalvik.system.NativeStart.main(Native Method)
不知道有没有人遇到过

**Comment by dlew** [comment]
This looks like a Proguard issue, where you're removing `BehaviorSubject` from the final APK.

**Comment by chenzhentao** [comment]
出现这个问题有两种情况,1:就是依赖包过多,做好分包,2,就是依赖冲突,列出来依赖树,查找那个冲突就可以了
