### ISSUE TITLE
 latest version Cause the webview to crash in android5.1

### ISSUE THREAD

**Issue by moneeWong** [trello/RxLifecycle#311]
or it is implementation 'androidx.appcompat:appcompat:1.1.0'

**Comment by dlew** [comment]
Could you provide more information?

**Comment by moneeWong** [comment]
https://stackoverflow.com/questions/41025200/android-view-inflateexception-error-inflating-class-android-webkit-webview
If this is the cause, please ignore it

**Comment by dlew** [comment]
The link you posted is from years ago and doesn't seem to have anything to do with this.

I'd be happy to figure out what's going wrong, but I need *at least* a stack trace to go off of.

**Comment by zzsakurazz** [comment]
android.content.res.Resources$NotFoundException: String resource ID #0x3040005
        at android.content.res.HwResources.getText(HwResources.java:1314)
        at android.content.res.Resources.getString(Resources.java:399)
        at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:733)
        at com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:657)
        at com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:649)
        at com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:798)
        at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:634)
        at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:571)
        at com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:313)
        at com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:98)
        at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:265)
        at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:125)
        at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:112)
        at com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
        at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:109)
        at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:262)
        at android.webkit.WebView.<init>(WebView.java:554)
        at android.webkit.WebView.<init>(WebView.java:489)
        at android.webkit.WebView.<init>(WebView.java:472)
        at android.webkit.WebView.<init>(WebView.java:459)
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
        at android.view.LayoutInflater.createView(LayoutInflater.java:626)
        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
        at com.android.internal.policy.impl.HwPhoneLayoutInflater.onCreateView(HwPhoneLayoutInflater.java:75)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:701)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:760)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:825)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:523)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:425)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:368)
        at com.ole.libwebview.BaseWebview.loadLayout(BaseWebview.java:61)
        at com.ole.libwebview.BaseWebview.<init>(BaseWebview.java:50)
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
        at android.view.LayoutInflater.createView(LayoutInflater.java:626)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:762)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:825)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:523)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:425)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:368)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
        at ola.com.travel.core.base.OlaBaseActivity.setContentView(OlaBaseActivity.java:73)
        at ola.com.travel.web.activity.CommonWebActivity.onCreate(CommonWebActivity.java:98)
        at android.app.Activity.performCreate(Activity.java:6100)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1109)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2401)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
        at android.app.ActivityThread.access$1200(ActivityThread.java:163)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1371)

**Comment by dlew** [comment]
That stack trace has nothing to do with this library. It doesn't even include an `RxLifecycle` class anywhere in the stack.

**Comment by moneeWong** [comment]
It can be reproduced in any project. You can try to create a new Demo and  implementation 'androidx.appcompat:appcompat:1.1.0'. When you run it on android 5.1, using webview will cause a crash.

**Comment by dlew** [comment]
Could you provide a demo project? I don't have time to reproduce your bugs for you. If you can clearly demonstrate an issue then I can look into it.

**Comment by moneeWong** [comment]
> Could you provide a demo project? I don't have time to reproduce your bugs for you. If you can clearly demonstrate an issue then I can look into it.

I've created a new project using only the RxLifecycle library and webView components, and you can test the project in your free time, thank you

https://github.com/trello/RxLifecycle/issues/311#issuecomment-541694879

**Comment by dlew** [comment]
I've checked out the demo and can't reproduce the crash (though I don't have a 5.1 device; I tested on a 6.0.1 device).

That said - there is **no usage of RxLifecycle in the demo**. You include it in the Gradle dependencies, sure, but you can actually remove them and the app still builds fine. Whatever is happening has nothing to do with RxLifecycle's implementation.

It is possible that RxLifecycle is bringing in a newer version of a dependency that is causing problems (e.g. a more recent version of AppCompat). But your beef should be with them, not with RxLifecycle
