### ISSUE TITLE
bindUntilEvent() on lifecycle() failes with 'ActivityEvent cannot be cast to rx.Observable'

### ISSUE THREAD

**Issue by forgemo** [trello/RxLifecycle#98]
I tried the following code,  based on your Kotlin example from the readme.

```kotlin
class MainActivity: RxAppCompatActivity() {
    
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        lifecycle()
        .bindUntilEvent(this, ActivityEvent.STOP)
        .subscribe({Log.d("Test", "Success")},{Log.e("Test", it.message, it)})
    }
}
```

I expected to see some "Success" log entries but got the following error.

Since my experience with RxJava and the RxLifecycle library is little, I am not sure whether my code is flawed or it is a bug.
```
E/Test: com.trello.rxlifecycle.ActivityEvent cannot be cast to rx.Observable
java.lang.ClassCastException: com.trello.rxlifecycle.ActivityEvent cannot be cast to rx.Observable
at com.trello.rxlifecycle.RxLifecycle$1.call(RxLifecycle.java:79)
at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:54)
at rx.internal.operators.NotificationLite.accept(NotificationLite.java:150)
at rx.subjects.SubjectSubscriptionManager$SubjectObserver.accept(SubjectSubscriptionManager.java:318)
at rx.subjects.SubjectSubscriptionManager$SubjectObserver.emitLoop(SubjectSubscriptionManager.java:291)
at rx.subjects.SubjectSubscriptionManager$SubjectObserver.emitFirst(SubjectSubscriptionManager.java:270)
at rx.subjects.BehaviorSubject$1.call(BehaviorSubject.java:106)
at rx.subjects.BehaviorSubject$1.call(BehaviorSubject.java:102)
at rx.subjects.SubjectSubscriptionManager.add(SubjectSubscriptionManager.java:100)
at rx.subjects.SubjectSubscriptionManager.call(SubjectSubscriptionManager.java:60)
at rx.subjects.SubjectSubscriptionManager.call(SubjectSubscriptionManager.java:35)
at rx.Observable$2.call(Observable.java:162)
at rx.Observable$2.call(Observable.java:154)
at rx.Observable$2.call(Observable.java:162)
at rx.Observable$2.call(Observable.java:154)
at rx.Observable$2.call(Observable.java:162)
at rx.Observable$2.call(Observable.java:154)
at rx.Observable.subscribe(Observable.java:8191)
at rx.Observable.subscribe(Observable.java:8158)
at rx.Observable.subscribe(Observable.java:7962)
at ninja.mess.templateapplication.activity.MainActivity.onCreate(MainActivity.kt:28)
at android.app.Activity.performCreate(Activity.java:5990)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
at android.app.ActivityThread.access$800(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: CREATE
at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:187)
at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:56)
at rx.internal.operators.NotificationLite.accept(NotificationLite.java:150) 
at rx.subjects.SubjectSubscriptionManager$SubjectObserver.accept(SubjectSubscriptionManager.java:318) 
at rx.subjects.SubjectSubscriptionManager$SubjectObserver.emitLoop(SubjectSubscriptionManager.java:291) 
at rx.subjects.SubjectSubscriptionManager$SubjectObserver.emitFirst(SubjectSubscriptionManager.java:270) 
at rx.subjects.BehaviorSubject$1.call(BehaviorSubject.java:106) 
at rx.subjects.BehaviorSubject$1.call(BehaviorSubject.java:102) 
at rx.subjects.SubjectSubscriptionManager.add(SubjectSubscriptionManager.java:100) 
at rx.subjects.SubjectSubscriptionManager.call(SubjectSubscriptionManager.java:60) 
at rx.subjects.SubjectSubscriptionManager.call(SubjectSubscriptionManager.java:35) 
at rx.Observable$2.call(Observable.java:162) 
at rx.Observable$2.call(Observable.java:154) 
at rx.Observable$2.call(Observable.java:162) 
at rx.Observable$2.call(Observable.java:154) 
at rx.Observable$2.call(Observable.java:162) 
at rx.Observable$2.call(Observable.java:154) 
at rx.Observable.subscribe(Observable.java:8191) 
at rx.Observable.subscribe(Observable.java:8158) 
at rx.Observable.subscribe(Observable.java:7962) 
at ninja.mess.templateapplication.activity.MainActivity.onCreate(MainActivity.kt:28) 
at android.app.Activity.performCreate(Activity.java:5990) 
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278) 
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
at android.app.ActivityThread.access$800(ActivityThread.java:151) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:135) 
at android.app.ActivityThread.main(ActivityThread.java:5254) 
at java.lang.reflect.Method.invoke(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:372)
```

These are my dependencies:

    compile 'com.android.support:appcompat-v7:23.2.1'
    compile 'io.reactivex:rxandroid:1.1.0'
    compile 'io.reactivex:rxjava:1.1.0'
    compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    compile 'com.trello:navi:0.2.0'
    compile 'com.trello:rxlifecycle:0.5.0'
    compile 'com.trello:rxlifecycle-components:0.5.0'
    compile 'com.trello:rxlifecycle-navi:0.5.0'
    compile 'com.trello:rxlifecycle-kotlin:0.5.0'

**Comment by dlew** [comment]
This inspired me to make #99, so I can test things Kotlin in action (since I don't normally use Kotlin for Android dev).

I wasn't able to reproduce your issue at all though. Are you sure there isn't something else going on? E.g., are you sure `this` is the `Activity`?

**Comment by forgemo** [comment]
Thank you for writing the Kotlin test! This helped me to identify my isssue. I tried your code and it threw the exact same exception as my code. Since this seemed quite suspicious to me, I completely uninstalled my app and tried your code again. I worked! My example is now working, too.

I, however, couldn't find out what caused the issue why only a complete "uninstall" did fix it.

**Comment by dlew** [comment]
Maybe a clean build is what it took? Or maybe it's an instant run problem? 

Regardless, good to have this sample around now for cases like this.
